scrape_configs:
    - job_name: cadvisor
      scrape_interval: 5s
      static_configs:
      - targets:
        - cadvisor:8080
    - job_name: node
      static_configs:
      - targets: ['131.3.50.189:9100']