version: '3.3'
services:
  redis:
    image: redis:latest
    ports:
      - "6789:6379"
    container_name: redis
    command: redis-server --requirepass "arknights"
    volumes:
      - "redis_data:/data"
      - "./redis.conf:/etc/redis/redis.conf"
      - "/etc/localtime:/etc/localtime"
      # - "/etc/timezone:/etc/timezone" # only ubuntu needed
    restart: always
    network_mode: "bridge"
  mongo:
    image: mongo:latest
    ports:
      - "27890:27017"
    container_name: mongo
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config_data: /data/configdb"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "beihai"
      MONGO_INITDB_ROOT_PASSWORD: "yaoduoxiang"
    restart: always
    network_mode: "bridge"

volumes:
  mongo_data:
    name: mongo_data
  mongo_config_data:
    name: mongo_config_data
  redis_data:
    name: redis_data


